// Setup.
export const SETUP_INIT = 'SETUP_INIT';
export const SETUP_SET_BALL_RANGE = 'SETUP_SET_BALL_RANGE';

// Lottery.
export const LOTTERY_RESET = 'LOTTERY_RESET';
export const LOTTERY_UPDATE_TEAM_LIST = 'LOTTERY_UPDATE_TEAM_LIST';
export const LOTTERY_START_NEW_ROUND = 'LOTTERY_START_NEW_ROUND';
export const LOTTERY_ADD_BALL = 'LOTTERY_ADD_BALL';
export const LOTTERY_SET_ROUND_WINNER = 'LOTTERY_SET_ROUND_WINNER';
export const LOTTERY_SET_ROUND_NOT_IN_PROGRESS = 'LOTTERY_SET_ROUND_NOT_IN_PROGRESS';
export const LOTTERY_SET_REDRAW_ROUND = 'LOTTERY_SET_REDRAW_ROUND';
export const LOTTERY_END = 'LOTTERY_END';
export const LOTTERY_SET_REMAINING_ORDER = 'LOTTERY_SET_REMAINING_ORDER';
